name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  check-format:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add git make clang

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Check format -> make format-check
      run: |
        make format-check
